import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "./layouts/Header";
import Footer from "./layouts/Footer";
import AuthSession from "@/AuthSession";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Travel U",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthSession>
          <Header />
          {children}
          <Footer />
        </AuthSession>
      </body>
    </html>
  );
}
